spring:
  datasource:
    url: jdbc:mysql://localhost:3306/module?serverTimezone=UTC
    username: root
    password: 123456
    #url: jdbc:mysql://localhost:3306/guttv_ums?zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    #username: root
    #password: Guttv@1234ABCxyz!
    #password: 123456
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filters: stat,wall,slf4j

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    locale: zh_CN
    time-zone: GMT+8
  thymeleaf:
    cache: true
  generator:
    package-name: com.guttv.ums.crm
    database-name: lean
  cache:
    jcache:
      config: classpath:ehcache.xml
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
