spring:
  datasource:
    url: jdbc:mysql://10.3.1.9:3306/guttv_ums?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: Guttv@1234ABCxyz!
  jackson:
    #date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    locale: zh_CN
    time-zone: GMT+8