spring:
  datasource:
    url: jdbc:mysql://10.3.1.16:3306/system?zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: hqh1@MDN@develop
     #url: jdbc:mysql://localhost:3306/guttv_ums?
    #password: Guttv@1234ABCxyz!
    #password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    locale: zh_CN
    time-zone: GMT+8
  thymeleaf:
    cache: false
  generator:
    package-name: com.guttv.ums.crm
  cache:
    jcache:
      config: classpath:ehcache.xml
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    root: info
    com.guttv.mapper: debug
